INSERT INTO users (name, age) VALUES ("Mary", 25);
INSERT INTO users (name, age) VALUES ("Bob", 40);
INSERT INTO users (name, age) VALUES ("Gary", 29);
INSERT INTO users (name, age) VALUES ("Anita", 19);
INSERT INTO users (name, age) VALUES ("Brian", 25);
INSERT INTO users (name, age) VALUES ("Wilson", 56);
INSERT INTO users (name, age) VALUES ("Sandra", 49);
INSERT INTO users (name, age) VALUES ("Tim", 38);
INSERT INTO users (name, age) VALUES ("Horrace", 32);
INSERT INTO users (name, age) VALUES ("Julie", 31);
INSERT INTO users (name, age) VALUES ("Karen", 34);
INSERT INTO users (name, age) VALUES ("Lee", 27);
INSERT INTO users (name, age) VALUES ("Liz", 43);
INSERT INTO users (name, age) VALUES ("Henry", 36);
INSERT INTO users (name, age) VALUES ("Steve", 47);
INSERT INTO users (name, age) VALUES ("Christina", 24);
INSERT INTO users (name, age) VALUES ("Paul", 25);
INSERT INTO users (name, age) VALUES ("Scarlet", 29);
INSERT INTO users (name, age) VALUES ("Louise", 28);
INSERT INTO users (name, age) VALUES ("Anthony", 53);

INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Big shoes", "Clown college", 300, 01012021, 01022021);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Catching pigglets", "Outreach", 78, 02052019, 030620202);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Fizzy", "Niche", 9, 03042018, 02022022);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Hunger games", "Death match", 1000000, 01011999, 01012029);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Inflatable badger", "Outreach", 876, 19102020, 19102021);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Cry-a-thon", "Niche", 540, 14022021, 14022021);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Rocketship", "Science", 90000000001, 01012021, 01012031);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Rocketship 2", "Science", 9000000002, 02012021, 02042021);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Books for hooks", "Outreach", 700, 10062021, 01092021);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Egg fight", "Serious", 80000, 04042020, 03032021);

INSERT INTO pledges (amount, user_id, project_id) VALUES (56, 8, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (4, 9, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (879, 20, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (54, 20, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (6544, 15, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (47, 18, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (111, 1, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (65, 17, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 2, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 14, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (578, 13, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (12, 12, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (65, 14, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (90, 5, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (321, 9, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 7, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15, 11, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (660, 16, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (400, 2, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (70, 3, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 7, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 19, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (40, 5, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (167, 11, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 17, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (499, 12, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (24, 4, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (3695, 20, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (35, 8, 4);